bunix:		main.cpp Process.h Process.cpp DefinitionFileParser.h DefinitionFileParser.cpp Semaphore.h Semaphore.cpp Printer.h Printer.cpp HardDrive.h HardDrive.cpp Cache.h Cache.cpp
			g++ -std=c++11 main.cpp Process.h Process.cpp DefinitionFileParser.h DefinitionFileParser.cpp Semaphore.h Semaphore.cpp Printer.h Printer.cpp HardDrive.h HardDrive.cpp Cache.h Cache.cpp -o bunix
