bunix:		main.cpp Process.h Process.cpp DefinitionFileParser.h DefinitionFileParser.cpp Semaphore.h Semaphore.cpp
			g++ -std=c++11 main.cpp Process.h Process.cpp DefinitionFileParser.h DefinitionFileParser.cpp Semaphore.h Semaphore.cpp -o bunix
