######################################################################
# Automatically generated by qmake (3.0) Fri May 26 17:07:37 2017
######################################################################

TEMPLATE = app
TARGET = "Hexadecimal Calculator"
INCLUDEPATH += .
QT += widgets
CONFIG += c++11

# Input
HEADERS += HexadecimalCalculator.h
SOURCES += HexadecimalCalculator.cpp main.cpp
